# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Robyn Overstreet
email: robynover@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://robynover.github.io" # the base hostname & protocol for your site
twitter_username: robynover
github_username:  robynover

# Build settings
markdown: kramdown
exclude: [vendor]
#remote_theme: pages-themes/cayman@v0.2.0
#theme: minima